repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.53.3
    hooks:
      - id: golangci-lint
  - repo: https://github.com/drmorr0/go-carpet
    rev: 641fb88
    hooks:
      - id: go-carpet
        args:
          - "-mincov=5"
