---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk-cloudprov
  namespace: default
  labels:
    app: sk-cloudprov
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk-cloudprov
  template:
    metadata:
      labels:
        app: sk-cloudprov
    spec:
      containers:
        - name: cloudprov
          image: localhost:5000/cloudprov:latest
          command:
            - /cloudprov
          securityContext:
            capabilities:
              add: ["SYS_PTRACE"]
      nodeSelector:
        type: kind-worker
