name: Publish Docs
on:
  push:
    branches:
      - 'master'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger remote workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/acrlabs/www/actions/workflows/publish.yml/dispatches \
          -d '{"ref":"master","inputs":{}}'
