name: verify code (lint, test)
on: [push]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
      - run: go test -v ./...
