name: code verification
on: [push]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo and build scripts
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: |
            .build
      - name: Add llvm-tools
        run: rustup component add llvm-tools-preview
      - name: Install grcov
        run: cargo install grcov
      # We use the golangci-lint action here instead of just calling make because
      # the provided action does much more aggressive caching
      - name: Lint Go code
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
      - name: Lint Rust code
        run: cargo clippy
      - name: Build
        run: make build
      # We don't call verify here because of the linting thing above
      - name: Test
        run: make test cover
        env:
          RUST_COVER_TYPE: lcov
      - name: Check coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: .build/coverage
